Hw11
ipotemkin/sky-react pull request #8
Opened 2022-07-05 07:40 UTC by ipotemkin

React Router

2022-07-06 07:14 UTC, mrerberg requested changes

2022-07-06 07:14 UTC, mrerberg commented on src/components/HexColors.js
>  function genColors(count) {
Старайся утилиты и хелперы в соответствующую папку или файлик класть в рамках компонента, у всего должно быть свое место. Общая практика

2022-07-06 07:14 UTC, mrerberg commented on src/pages/book_cart/index.jsx
> +    books.forEach(element => {
Можно элегантнее через reduce сделать

2022-07-06 07:14 UTC, mrerberg commented on src/pages/page404/index.jsx
> +    {/* <nav>
Мертвый код лучше удалить

2022-07-06 07:17 UTC, ipotemkin commented on src/pages/page404/index.jsx
> +    {/* <nav>
Исправил

2022-07-06 07:25 UTC, ipotemkin commented on src/components/HexColors.js
>  function genColors(count) {
Исправил

2022-07-06 07:46 UTC, ipotemkin commented on src/pages/book_cart/index.jsx
> +    books.forEach(element => {
Переделал. Но, мне кажется, я как-то сравнивал разные варианты, и скорость была не на стороне reduce. Возможно, я уже не помню

2022-07-07 05:44 UTC, mrerberg approved these changes

2022-07-07 05:44 UTC, mrerberg commented on src/pages/order/index.jsx
> +  const calcTotal = (field) => books.reduce((sum, current) => sum + current[field], 0)
Имей в виду, передавай дефолтное значение в редьюс, увеличиваешь операцию на 1. Так как в первой итерации 0 складывается с первым числом в массиве

2022-07-07 09:25 UTC, merged